CREATE TABLE IF NOT EXISTS audit_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  action VARCHAR(128) NOT NULL,
  user_id INT NULL,
  user_role VARCHAR(64) NULL,
  user_name VARCHAR(128) NULL,
  meta JSON NULL
);

