CREATE TABLE IF NOT EXISTS auth_tokens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  token VARCHAR(255) NOT NULL UNIQUE,
  user_id INT NULL,
  tenant_id INT NULL,
  role VARCHAR(64) NOT NULL,
  user_name VARCHAR(128) NULL,
  user_email VARCHAR(160) NULL,
  expires_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

