CREATE TABLE IF NOT EXISTS device_events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  device_id VARCHAR(64) NOT NULL,
  employee_id INT NOT NULL,
  event VARCHAR(32) NOT NULL,
  occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

